---
name: Close Stale Issues and PRs
on: [pull_request,workflow_dispatch]

permissions:
  contents: write # only for delete-branch option
  issues: write
  pull-requests: write

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1

    steps:
      - name: Fetch actions (v3)
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Close Stale Issues
        uses: actions/stale@v5.2.1
